name: Test Nginx Reverse Proxy

on: [push, pull_request]

jobs:
  test-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Nginx with static HTML
      run: |
        docker run -d --name test-nginx -p 8080:80 \
          -v "${{ github.workspace }}/nginx-proxy/html:/usr/share/nginx/html:ro" \
          nginx:latest

    - name: Wait for Nginx to boot
      run: sleep 5

    - name: Curl Test
      run: curl -sSf http://localhost:8080

    - name: Cleanup
      if: always()
      run: docker rm -f test-nginx || true
